# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/nowi74/Downloads/kcu105-xdc-rdf0349/KCU105_Rev1.0_02292016.xdc

# Block Designs: bd/multi_cycle_fib/multi_cycle_fib.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==multi_cycle_fib || ORIG_REF_NAME==multi_cycle_fib} -quiet] -quiet

# IP: bd/multi_cycle_fib/ip/multi_cycle_fib_multicycle_cpu_0_0/multi_cycle_fib_multicycle_cpu_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==multi_cycle_fib_multicycle_cpu_0_0 || ORIG_REF_NAME==multi_cycle_fib_multicycle_cpu_0_0} -quiet] -quiet

# IP: bd/multi_cycle_fib/ip/multi_cycle_fib_clk_wiz_0_0/multi_cycle_fib_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==multi_cycle_fib_clk_wiz_0_0 || ORIG_REF_NAME==multi_cycle_fib_clk_wiz_0_0} -quiet] -quiet

# XDC: bd/multi_cycle_fib/multi_cycle_fib_ooc.xdc
