# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/nowi74/cpuex2020_1/1st/core/src/kcu105-xdc-rdf0349/KCU105_Rev1.0_02292016.xdc

# Block Designs: bd/arch_1st/arch_1st.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arch_1st || ORIG_REF_NAME==arch_1st} -quiet] -quiet

# IP: bd/arch_1st/ip/arch_1st_multicycle_cpu_0_0/arch_1st_multicycle_cpu_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arch_1st_multicycle_cpu_0_0 || ORIG_REF_NAME==arch_1st_multicycle_cpu_0_0} -quiet] -quiet

# IP: bd/arch_1st/ip/arch_1st_clk_wiz_0_0/arch_1st_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arch_1st_clk_wiz_0_0 || ORIG_REF_NAME==arch_1st_clk_wiz_0_0} -quiet] -quiet

# XDC: bd/arch_1st/arch_1st_ooc.xdc
