#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Mon Oct 12 18:57:13 JST 2020
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto e2f13862cf92486fba079423fce1203f --incr --debug typical --relax --mt 8 -L xil_defaultlib -L sim_clk_gen_v1_0_2 -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot multi_fib_wrapper_behav xil_defaultlib.multi_fib_wrapper xil_defaultlib.glbl -log elaborate.log"
xelab -wto e2f13862cf92486fba079423fce1203f --incr --debug typical --relax --mt 8 -L xil_defaultlib -L sim_clk_gen_v1_0_2 -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot multi_fib_wrapper_behav xil_defaultlib.multi_fib_wrapper xil_defaultlib.glbl -log elaborate.log

