#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Oct 12 18:57:14 JST 2020
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim multi_fib_wrapper_behav -key {Behavioral:sim_1:Functional:multi_fib_wrapper} -tclbatch multi_fib_wrapper.tcl -protoinst "protoinst_files/multi_fib.protoinst" -protoinst "protoinst_files/single_fib.protoinst" -view /home/nowi74/cpuex2020_1/fib/core/vivado_prj/mips_processor/single_fib_wrapper_behav.wcfg -log simulate.log"
xsim multi_fib_wrapper_behav -key {Behavioral:sim_1:Functional:multi_fib_wrapper} -tclbatch multi_fib_wrapper.tcl -protoinst "protoinst_files/multi_fib.protoinst" -protoinst "protoinst_files/single_fib.protoinst" -view /home/nowi74/cpuex2020_1/fib/core/vivado_prj/mips_processor/single_fib_wrapper_behav.wcfg -log simulate.log

