webtalk_init -webtalk_dir C:/Users/nowi74/OneDrive/cpuexcore/1st/core/1st_architecture/1st_architecture.sim/sim_1/behav/xsim/xsim.dir/arch_1st_wrapper_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Nov 22 19:20:53 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2729669" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211142045_1777515821_210725329_264" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "982e6577-e4f6-4df9-a4de-613c523001aa" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "01961f57f7a14896be55f584f33c857b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "177" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2208 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "2119435 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "2.20_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "19556_KB" -context "xsim\\usage"
webtalk_transmit -clientid 211824686 -regid "211142045_1777515821_210725329_264" -xml C:/Users/nowi74/OneDrive/cpuexcore/1st/core/1st_architecture/1st_architecture.sim/sim_1/behav/xsim/xsim.dir/arch_1st_wrapper_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/nowi74/OneDrive/cpuexcore/1st/core/1st_architecture/1st_architecture.sim/sim_1/behav/xsim/xsim.dir/arch_1st_wrapper_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/nowi74/OneDrive/cpuexcore/1st/core/1st_architecture/1st_architecture.sim/sim_1/behav/xsim/xsim.dir/arch_1st_wrapper_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
